pipeline:
  name: pipeline-286
  identifier: pipeline286
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: git286
        build: <+input>
  stages:
    - stage:
        name: dontet
        identifier: dontet
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get install dotnet-sdk-7.0 
                      dotnet restore
                      dotnet build --configuration Release
                      dotnet test
